refactor: metadata
aragon/token-voting-plugin-hardhat pull request #21
Opened 2024-04-15 10:13 UTC by Michael-A-Heuer

2024-04-19 07:39 UTC, josemarinas submitted a review, later dismissed

2024-04-19 09:28 UTC, clauBv23 approved these changes, later dismissed

2024-04-23 14:24 UTC, clauBv23 submitted a review, later dismissed

2024-04-23 14:30 UTC, jordaniza requested changes

2024-04-23 14:30 UTC, jordaniza commented on packages/contracts/deploy/30_upgrade_repo/31a_upgrade_repo.ts
> + * It MUST NOY be called if the contract requires reinitialization, because this
```suggestion
 * It MUST NOT be called if the contract requires reinitialization, because this
```

2024-04-23 14:33 UTC, clauBv23 approved these changes

2024-04-23 14:33 UTC, jordaniza approved these changes

2024-04-23 14:44 UTC, merged