Feat/os 830/token voting/stop granting upgrade plugin permission dao
aragon/token-voting-plugin-hardhat pull request #23
Opened 2024-05-07 09:16 UTC by clauBv23

2024-05-07 11:21 UTC, Rekard0 commented on packages/contracts/src/TokenVotingSetup.sol
> +            permissions[2] = PermissionLib.MultiTargetPermission({
I would also not revoke this permission,
because uninstalling the plugin dose not mean we should revoke mint permission 
the token still belong to the DAO

@Michael-A-Heuer & @jordaniza for vis & opinion

2024-05-07 14:39 UTC, Michael-A-Heuer requested changes
Some small improvments and minor suggestions.
The contract changes look good to me.

2024-05-07 14:39 UTC, Michael-A-Heuer commented on packages/contracts/CHANGELOG.md
> +- Updated `prepareUpdate` function in `TokenVotingSetup` to revoke the `UPGRADE_PLUGIN_PERMISSION_ID` from earlier plugin builds when it was granted.
```suggestion
- Changed the `prepareInstallation` function in `TokenVotingSetup` to not unnecessarily grant the `UPGRADE_PLUGIN_PERMISSION_ID` permission to the installing DAO.
- Changed the `prepareUpdate` function in `TokenVotingSetup` to revoke the previously unnecessarily granted `UPGRADE_PLUGIN_PERMISSION_ID` permission from the installing DAO.
```

2024-05-07 14:39 UTC, Michael-A-Heuer commented on packages/contracts/src/build-metadata.json
> +  "change": "v1.3\n - Removed the unnecessary permission for the Dao to upgrade the plugin. This permission granted on previous versions, will be automatically removed during update.\n",
```suggestion
  "change": "v1.3\n - Removed an unneccessary permission that allowed the Dao to upgrade the plugin, because this is supposed to happens as part of the update itself. The unnecessary permission, which was granted on installation of previous versions, will be automatically removed with the update to this version.\n",
```

2024-05-07 14:39 UTC, Michael-A-Heuer commented on packages/contracts/test/10_unit-testing/12_plugin-setup.ts
> +    it('update from build 1 should return correct permissions', async () => {
A good style for test naming is to have a readable sentence, e.g.,
```suggestion
    it('returns the permissions expected for the update from build 1', async () => {
```

2024-05-07 14:39 UTC, Michael-A-Heuer commented on packages/contracts/test/10_unit-testing/12_plugin-setup.ts
> +    it('update from build 2 should return correct permissions', async () => {
see above

2024-05-07 14:39 UTC, Michael-A-Heuer commented on packages/contracts/test/10_unit-testing/12_plugin-setup.ts
> +      // const prepareUpdateData
```suggestion
```

2024-05-07 14:39 UTC, Michael-A-Heuer commented on packages/contracts/test/10_unit-testing/12_plugin-setup.ts
> +      // const prepareUpdateData
```suggestion
```

2024-05-07 14:39 UTC, Michael-A-Heuer commented on packages/contracts/test/20_integration-testing/21_deployment.ts
Let's revert this in this PR. We should fix it in the template and sync this fork.

2024-05-07 14:39 UTC, Michael-A-Heuer commented on packages/contracts/test/20_integration-testing/test-helpers.ts
> +  // Install previous plugin build (build previous to the latest one)
```suggestion
  // Install a previous build with build number `build`
```
Is this better? Feel free to ignore this if you disagree.

2024-05-07 14:39 UTC, Michael-A-Heuer commented on packages/contracts/test/20_integration-testing/test-helpers.ts
> +  // Update current build (a previous one) to the latest build
```suggestion
  // Update from the previous build to the latest build
```
Is this better?

2024-05-07 14:42 UTC, heueristik commented on packages/contracts/src/TokenVotingSetup.sol
> +            permissions[2] = PermissionLib.MultiTargetPermission({
> because uninstalling the plugin dose not mean we should revoke mint permission on the token

I agree with this statement, but don't see where the `MINT_PERMISSION_ID` permission is revoked. Maybe this comment is outdated by now. 
Please clarify @clauBv23

2024-05-07 14:43 UTC, clauBv23 commented on packages/contracts/test/10_unit-testing/12_plugin-setup.ts
> +    it('update from build 2 should return correct permissions', async () => {
fixed in https://github.com/aragon/token-voting-plugin/pull/23/commits/aab361221c9002adba42547312a79ea504f378f2

2024-05-07 14:46 UTC, clauBv23 commented on packages/contracts/test/20_integration-testing/21_deployment.ts
https://github.com/aragon/token-voting-plugin/pull/23/commits/73272f8355d4ef84680c431aca725c7a7662858c

2024-05-07 14:49 UTC, Michael-A-Heuer approved these changes

2024-05-07 15:02 UTC, clauBv23 commented on packages/contracts/src/TokenVotingSetup.sol
> +            permissions[2] = PermissionLib.MultiTargetPermission({
I think he is not talking about a change made by this PR, but what is already being done [here](https://github.com/aragon/token-voting-plugin/blob/d02945604a049e385e4da9285acc360c3c21cdbe/packages/contracts/src/TokenVotingSetup.sol#L271-L282). 
The `MINT_PERMISSION_ID` on the token is revoked to the Dao when the plugin is uninstalled. 
There is a comment explaining the rationale 
>// Revocation of permission is necessary only if the deployed token is GovernanceERC20,
        // as GovernanceWrapped does not possess this permission. Only return the following
        // if it's type of GovernanceERC20, otherwise revoking this permission wouldn't have any effect.

but I also agree with Sarkawt, maybe this should not be revoked when uninstalling.

2024-05-07 15:04 UTC, Michael-A-Heuer commented on packages/contracts/test/20_integration-testing/test-helpers.ts
> +  // Update from the previous build to the latest build
Probably, this must also be changed on the template.

2024-05-08 07:43 UTC, Rekard0 commented on packages/contracts/src/TokenVotingSetup.sol
> +            permissions[2] = PermissionLib.MultiTargetPermission({
i dont see why it is out of scope, we are correcting how the setup handling permission
and it is an easy fix,
remove:
```
// Revocation of permission is necessary only if the deployed token is GovernanceERC20,
        // as GovernanceWrapped does not possess this permission. Only return the following
        // if it's type of GovernanceERC20, otherwise revoking this permission wouldn't have any effect.
        if (isGovernanceERC20) {
            permissions[2] = PermissionLib.MultiTargetPermission({
                operation: PermissionLib.Operation.Revoke,
                where: token,
                who: _dao,
                condition: PermissionLib.NO_CONDITION,
                permissionId: GovernanceERC20(token).MINT_PERMISSION_ID()
            });
        }
        ```

2024-05-08 07:45 UTC, Rekard0 commented on packages/contracts/src/TokenVotingSetup.sol
> +            permissions[2] = PermissionLib.MultiTargetPermission({
> I think he is not talking about a change made by this PR, but what is already being done [here](https://github.com/aragon/token-voting-plugin/blob/d02945604a049e385e4da9285acc360c3c21cdbe/packages/contracts/src/TokenVotingSetup.sol#L271-L282). The `MINT_PERMISSION_ID` on the token is revoked to the Dao when the plugin is uninstalled. There is a comment explaining the rationale
> 
> > // Revocation of permission is necessary only if the deployed token is GovernanceERC20,
> > // as GovernanceWrapped does not possess this permission. Only return the following
> > // if it's type of GovernanceERC20, otherwise revoking this permission wouldn't have any effect.
> 
> but I also agree with Sarkawt, maybe this should not be revoked when uninstalling.
> 
> Still, it looks out of this scope IMO, so I would create a new task to address it.

can you explain why it could be out of scope?

2024-05-09 09:34 UTC, Rekard0 approved these changes

2024-05-10 08:04 UTC, merged